### ISSUE TITLE
Persistence

### ISSUE THREAD

**Issue by KenanSulayman** [fullcontact/lmdb-zero#2]
Hey,

I'm trying to add this as a cache to one of our toolchain components, but I have problems with data not being persisted. I have 500 keys that contain json data and I am writing a u64 and a [u8] for each of them. Additionally, after each commit I am calling env#sync(true), but after restarting the tool, only half of the keys are there.

Specifically, this is a snippet from the impl that is used to persist data with lmdb-zero:

```
pub struct Memory<'a> {
    lmdb_env: &'a lmdb::Environment,
    lmdb_db: &'a lmdb::Database<'a>
}

impl<'a> Memory<'a> {
    #[inline]
    pub fn new (lmdb_env: &'a lmdb::Environment, lmdb_db: &'a lmdb::Database) -> Memory<'a> {
        Memory {
            lmdb_env: lmdb_env,
            lmdb_db: lmdb_db
        }
    }

    pub fn sync (&self) {
        self.lmdb_env.sync(true);
    }

    #[inline]
    pub fn put (&mut self, key: &str, data: &Vec<u8>) {
        let tx = lmdb::WriteTransaction::new(&self.lmdb_env).unwrap();

        {
            let mut access = tx.access();

            access.put(&self.lmdb_db, key, data.as_lmdb_bytes(), lmdb::put::Flags::empty()).unwrap();
        }

        tx.commit().unwrap();

        self.sync();
    }

    #[inline]
    pub fn put_u64 (&mut self, key: &str, data: &u64) {
        let tx = lmdb::WriteTransaction::new(&self.lmdb_env).unwrap();

        {
            let mut access = tx.access();

            access.put(&self.lmdb_db, key, data, lmdb::put::Flags::empty()).unwrap();
        }

        tx.commit().unwrap();

        self.sync();
    }

    /* other methods here */
}
```

There's one method used that effectively does a 7200 second cache per URL:

```
    fn client_cond_get (url: &str,
                        memory: &mut memory::Memory,
                        client: &client::HTTP
                    ) -> Vec<u8> {
        /* unixtime */
        let now = time::now().to_timespec().sec as u64;

        let mut url_ts_id = url.to_string();
                url_ts_id.push_str(&"_ts");

        let known_url_ts = memory.get_u64(&url_ts_id);

        if known_url_ts.is_some() {
            if (now - known_url_ts.unwrap()) < 7200 {
                return memory.get(&url).unwrap();
            }
        }

        let res = client.get(url);

        let _ = memory.put_u64(&url_ts_id, &now);

        memory.put(&url, &res);

        res
    }
```

So per http "get" operation there are at worst 2 reads and 2 puts, at best 2 reads (when data is obtained from the cache).

Could you maybe help me brainstorm possible issues I should be aware of when doing a commit? I am aware of the fact that a commit is writing to disk, but I don't know how to deal best with the OS disk buffering.

Thanks a lot.

Take this as a gift: 🍻

**Comment by KenanSulayman** [comment]
Hm, it seems `entires` doesn't change. (I did a env.stat() after each write)

Could it be that lmdb silently fails to write the keys?

**Comment by KenanSulayman** [comment]
Oh. It seems when writing a u64, it sometimes cannot be obtained correctly as a u64 back:

<img width="373" alt="bildschirmfoto 2016-10-17 um 23 55 21" src="https://cloud.githubusercontent.com/assets/280212/19457143/3f3e2fb6-94c5-11e6-8ac5-163688654790.png">

**Comment by AltSysrq** [comment]
> It seems when writing a u64

You may have been bitten by [alignment requirements](https://api.fullcontact.com/v3/docs/rustdoc/lmdb_zero/traits/trait.LmdbRaw.html#alignment). I'll need to look into how to make this problem more obvious, especially since if you're not using `LmdbRaw` yourself you wouldn't even have seen the warning. You probably want to read and write `Unaligned<u64>` instead of a bare `u64` ([docs](https://api.fullcontact.com/v3/docs/rustdoc/lmdb_zero/struct.Unaligned.html)). In these cases, I usually do something like

```rust
use lmdb::Unaligned as U;

// ...

let value: U<u64> = access.get(&db, "somekey").unwrap();
```

> I don't know how to deal best with the OS disk buffering.

You don't need to; the OS will maintain a coherent view of the file for all processes. The only thing `sync` accomplishes is that it tells the OS to actually write the data to disk so it is still there if a power failure occurs.

**Comment by KenanSulayman** [comment]
Nice, that worked like a charm. Thanks a lot.

**Comment by AltSysrq** [comment]
Version 0.3.0 has some changes that will help with this kind of problem:

- Value rejection errors now have error messages indicating the exact problem and pointing to relevant documentation.

- This particular instance — trying to get a bare `&u64` — is now a hard compile-time error as the bare primitive types other than `i8` and `u8` are no longer `LmdbRaw`, but _must_ be wrapped with `Unaligned`.

**Comment by KenanSulayman** [comment]
Great, thanks a lot!
